default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

env_credentials: &env_credentials
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV.fetch('POSTGRES_HOST') %>
  port: <%= ENV.fetch('POSTGRES_PORT') {5432} %>

development:
  <<: *default
  <<: *env_credentials
  database: authority_development

test:
  <<: *default
  <<: *env_credentials
  database: authority_test

production:
  primary: &primary_production
    <<: *default
    database: authority_production
    username: authority
    password: <%= ENV["AUTHORITY_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: authority_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: authority_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: authority_production_cable
    migrations_paths: db/cable_migrate
